// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEuIwec6Spi15XO94nJ4jeUk0QSSK5qIw',
    appId: '1:663120784220:web:c145586214b000311cef99',
    messagingSenderId: '663120784220',
    projectId: 'shadow-space-83b94',
    authDomain: 'shadow-space-83b94.firebaseapp.com',
    storageBucket: 'shadow-space-83b94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTU064ACEjvC-aQD2jxpMEuR2Iruk2Gic',
    appId: '1:663120784220:android:c3045ac64998c41d1cef99',
    messagingSenderId: '663120784220',
    projectId: 'shadow-space-83b94',
    storageBucket: 'shadow-space-83b94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARLnwts3y2cIrTBzjSBPvBE1krrTcnK6E',
    appId: '1:663120784220:ios:977cd390bb321d421cef99',
    messagingSenderId: '663120784220',
    projectId: 'shadow-space-83b94',
    storageBucket: 'shadow-space-83b94.firebasestorage.app',
    androidClientId: '663120784220-jsbadg8c5r8b2g207iud9s48bvvj9ndi.apps.googleusercontent.com',
    iosClientId: '663120784220-77usiev60tptdf2acjs42r69bbgn3s30.apps.googleusercontent.com',
    iosBundleId: 'com.example.shadowSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARLnwts3y2cIrTBzjSBPvBE1krrTcnK6E',
    appId: '1:663120784220:ios:977cd390bb321d421cef99',
    messagingSenderId: '663120784220',
    projectId: 'shadow-space-83b94',
    storageBucket: 'shadow-space-83b94.firebasestorage.app',
    androidClientId: '663120784220-jsbadg8c5r8b2g207iud9s48bvvj9ndi.apps.googleusercontent.com',
    iosClientId: '663120784220-77usiev60tptdf2acjs42r69bbgn3s30.apps.googleusercontent.com',
    iosBundleId: 'com.example.shadowSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEuIwec6Spi15XO94nJ4jeUk0QSSK5qIw',
    appId: '1:663120784220:web:4e0b31addf08f16f1cef99',
    messagingSenderId: '663120784220',
    projectId: 'shadow-space-83b94',
    authDomain: 'shadow-space-83b94.firebaseapp.com',
    storageBucket: 'shadow-space-83b94.firebasestorage.app',
  );
}
